version: "3.6"

services:
  crud-server:
    container_name: "crud-server"
    build: .docker/webserver
    ports:
      - 8081:80
    volumes:
      - ./public:/var/www/html
  crud-mysql:
    container_name: "crud-mysql"
    image: mysql:latest
    ports:
      - 3308:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=asdf000
      - MYSQL_DATABASE=crud